ansible: Autospec creation for update from version 2.7.8 to version 2.7.9
Abhijeet Kasurde (1):
      [Backport 2.7] VMware: Handle customValue in inventory

Alan Rominger (1):
      Plugin errors backport (#52749)

Albert Cervera i Areny (1):
      Filter DNSimple request by record name. (#49981)

Aniket Khisti (1):
      Fix trackback on providing arguemnt --all to ansible-doc command (#52034)

Brian Coca (4):
      Loader invalid plugin nicer error (#52754)
      Ensure play order is obeyed (#49897)
      properly convert inputs to handle bytes/unicode (#53072) (#53124)
      allow nontype configdata (#53365)

Chris Adams (1):
      docs: SAN prefixes are required for openssl_csr (#53144)

Dag Wieers (2):
      [Backport 2.7] Add missing ConnectionError imports
      ACI: Fix examples in documentation

Felix Fontein (25):
      Don't die when kernel memory accounting is not supported by runc build. (#53163)
      docker_swarm: hopefully fix debug CI problems, and fix check mode (#52825)
      Improve documentation on remote_addrs. (#52893)
      docker_swarm: make labels work with older docker daemon versions (#52895)
      docker_swarm: fix idempotency (#52976)
      docker_swarm: extend tests (part I) (#53005)
      Fix force when state==present. (#53003)
      docker_swarm: fix ca_force_rotate idempotency (#53039)
      docker_swarm: more integration tests (#53035)
      Diff feature is only available in devel.
      [2.7] openssl_certificate, fixed has_expired to check the cert expiration date (#53203)
      [2.7] docker_swarm_service: fix problem with UpdateConfig on certain docker daemons (#53224)
      docker_swarm: support older docker-py versions (#53129)
      Make clear which option is used by which provider. (#53208)
      [2.7] docker_swarm_service: don't crash when publish isn't specified (#53262)
      [stable-2.7] Python 2: accept both long and int for type=int (module options) (#53289)
      openssl_certificate: make sure extensions are present when they are queried by assertonly (#53207)
      2.7 way to make sure no SANs are there.
      openssl_csr: improve invalid SAN error messages (#53201)
      [2.7] docker_swarm_service: rename return variable to swarm_service (#53408)
      Warn user to send a password if the privatekey is password protected (#53360) (#53527)
      Trying to work around spurious test failures. (#53472)
      openssl_csr: improve subject validation (#53198)
      [2.7] docker_swarm: removing nodes requires docker >= 2.4.0 (#53592)
      docker_container: show warnings, fix/improve tests (#53440)

Jakob Ackermann (1):
      [docker_image] fix the changed state for tagging and pushing (#53451)

Jason Witkowski (1):
      apply node_id parameter to swarm node removal (#53503)

Jiri Tyr (2):
      Updating update_url for jenkins_plugin (#52086) (#52536)
      Fixing state=present for jenkins_plugin module (#52051) (#52535)

Jordan Borean (13):
      test suse: get tests working on newer OpenSUSE distributions (#52539)
      win_chocolatey - fix beta version parsing (#52601)
      fix filesystem tests on OpenSUSE 15+ (#52716)
      test - add Python 3 package for OpenSUSE in setup_openssl (#52775)
      test - add setup target that creates the nobody user (#52750)
      Suse add py3 package vars (#52794)
      OpenSUSE - Add OpenSUSE 15 test containers (#52793)
      win_certificate_store - Fix exception handling typo (#52906)
      winrm - try and recover from a send input failure (#53187)
      win_chocolatey_source - fix state=disabled with no source (#53097)
      re-add EAP to Stop for older branch
      win_domain: fix issue when running without credential delegation (#53480)
      test: fix get_url issues in CI for Ubuntu 14.04

Mario Lenz (1):
      [Backport 2.7] VMware: Fix KeyError in vmware_host_config_manager

Matt Clay (1):
      [stable-2.7] Keep existing to_yaml behavior with pyyaml >= 5.1. (#53772)

Matt Martz (1):
      [stable-2.7] Allow dict2items to work with hostvars (#53538).

Pablo Piaggio (1):
      Backport/2.7/51853 (#53153)

Philippe Makowski (1):
      fix bug #47154 (#49881)

Piotr Wojciechowski (1):
      Documentation update for labels operations on swarm/node (#53083)

Rene Moser (2):
      [2.7]: dnsimple: fix KeyError: 'record_type'  (#52646)
      [2.7] cloudscale: fix compatibilty with older py3 versions (#52822) (#52915)

Ryan Conway (1):
      Backport/2.7/51953 (#53657)

S (1):
      Fixed win_file crash with hidden files (#52584)

Sam Doran (2):
      [stable-2.7] Modify the correct variable when setting available hashing algorithms (#52994)
      [stable-2.7] Ensure Clear Linux parsing is actually parsing a Clear Linux host and all others fall back to NA (#53298) (#53541)

Sandra McCann (3):
      add link to AWS module details (#53126)
      backport correct examples (#53411)
      Clarify that do until loops are unsupported on include tasks (#49581) (#53628)

Sloane Hertel (2):
      Mark ec2_vpc_vgw as disabled to avoid hitting the resource limit (#53082)
      use composed vars in constructed groups (#53152)

Till Maas (1):
      rhsm_repository: Properly handle no repos (#51938)

Timo Runge (2):
      module_utils/mysql: Fixing unexpected keyword argument 'cursorclass' error after migratio… (#47809)
      Fix for "AttributeError: 'module' object has no attribute 'cursors'" (#49191) (#53445)

Tony Finch (1):
      get_url: return no change in check mode when checksum matches

Toshio Kuratomi (2):
      Update Ansible release version to v2.7.8.post0.
      New release v2.7.9

Tuan Anh Hoang-Vu (1):
      [backport 2.7] Fixed lvol ValueError with float size. (#52836)

Wojciech Sciesinski (1):
      Don't run integration tests for OS'es older than Windows 2016 (#53057)

Zim Kalinowski (1):
      Backport/2.7/52540 (#52545)

arsenicks (1):
      Backport into 2.7

plumbeo (1):
      backport/2.7/40092  (#51909)

rockandska (1):
      Fix idempotence in rabbitmq_plugin (#52166)

s-hertel (2):
      fix no_log indentation so AWS temporary credentials aren't displayed in tests
      If the private_ip has been provided for the new network interface it shouldn't also be added to top level parameters for run_instances